{"author":"439205512425504771","bot":true,"channel":"343299242963763200","content":"```py\nTraceback (most recent call last):\n  File \"source_file.py\", line 1, in <module>\n    print(x)\nNameError: name 'x' is not defined\n```","created":1528241801540,"id":"453703742164959242","server":"343179912196128792"}